import { Metadata } from "next";
import Head from "next/head";
import React from "react";
import Header from "./Header";
import Footer from "./Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Layout({ children }: any) {
  return (
    <div>
      <Head>
        <title>BrilleBeauty</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="BrilleBeauty" />
      </Head>

      <Header />

      {children}

      <Footer />
    </div>
  );
}

export default Layout;
